criação de CI
DadosAbertosDeFeira/iac-role-services pull request #3
Opened 2021-05-24 20:56 UTC by glenonmateus

cria um ci para a role service

2021-08-01 17:55 UTC, gomex requested changes

2021-08-01 17:55 UTC, gomex commented on molecule/default/molecule.yml
> +  - name: instance
Manter o nome talvez seja melhor.

2021-08-02 11:46 UTC, glenonmateus commented on molecule/default/molecule.yml
> +  - name: instance
ajuste feito, nome foi mantido

2021-08-13 20:35 UTC, gomex approved these changes

2021-08-13 20:36 UTC, merged